Repository jgnagy/metatron, pull requests merged in 2023-07, with the labels that each got.

#1 Added auto-magical kind detection and tests
  Gemfile.lock
  lib/metatron/template.rb
  lib/metatron/version.rb
  spec/metatron/template_spec.rb
Labels: enhancement

#3 Add alias methods to PersistentVolumeClaim
  lib/metatron/templates/persistent_volume_claim.rb
Labels: refactor

#4 Adding a complex cron job test
  spec/metatron/templates/cron_job_spec.rb
Labels: testing

#5 Unified pod approach to fix pod templates
  Gemfile.lock
  lib/metatron/templates/concerns/pod_producer.rb
  lib/metatron/templates/cron_job.rb
  lib/metatron/templates/daemon_set.rb
  lib/metatron/templates/deployment.rb
  lib/metatron/templates/job.rb
  lib/metatron/templates/pod.rb
  lib/metatron/templates/replica_set.rb
  lib/metatron/templates/stateful_set.rb
  lib/metatron/version.rb
  spec/metatron/templates/cron_job_spec.rb
  spec/metatron/templates/job_spec.rb
  spec/metatron/templates/stateful_set_spec.rb
Labels: refactor, testing
